name: WantedPlayers
main: org.toni_4819.wantedPlayers.WantedPlayers
version: '1.1'
api-version: 1.21
author: Toni_4819
description: Adds Wanted levels and rewards based on killstreaks.

# Hard dependencies: plugin will not load without them
depend: [PlaceholderAPI, Vault, pvpstats]

# Soft dependencies: optional, plugin adapts if present
softdepend: [LuckPerms]

commands:
  wantedreload:
    description: Reload the WantedPlayers configuration
    permission: wanted.reload

permissions:
  wanted.reload:
    description: Allows reloading the config
    default: op