name: Build

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Gradle
        uses: ./.github/actions/setup-gradle

      - name: Build plugin
        run: ./gradlew clean build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: plugin
          path: build/libs/*.jar
